
    create table tb_booked_seat (
        seat_price numeric(38,2),
        booking_id bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        seat_id bigint,
        updated_at timestamp(6),
        primary key (id)
    );

    create table tb_booking (
        total_price numeric(38,2),
        created_at timestamp(6),
        expires_at timestamp(6),
        id bigint generated by default as identity,
        session_fk bigint,
        updated_at timestamp(6),
        user_fk bigint,
        checkout_url varchar(1024),
        booking_status varchar(255) check (booking_status in ('AWAITING_DELETION', 'AWAITING_CANCELLATION','PAST','EXPIRED','CANCELLED','PAYMENT_CONFIRMED','PAYMENT_RETRY','AWAITING_PAYMENT')),
        checkout_id varchar(255),
        payment_intent_id varchar(255),
        refund_id varchar(255),
        qr_code_validated boolean not null,
        primary key (id)
    );

    create table tb_movie (
        minutes_duration integer not null,
        release_date date,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        poster_url varchar(2048),
        description varchar(255),
        genre varchar(255) check (genre in ('ACTION','COMEDY','DRAMA','HORROR','SCI_FI','THRILLER','ROMANCE','ANIMATION','DOCUMENTARY','FANTASY','MYSTERY','SPORTS','WESTERN','HISTORICAL')),
        title varchar(255),
        primary key (id)
    );

    create table tb_screen (
        created_at timestamp(6),
        id bigint generated by default as identity,
        theater_fk bigint,
        updated_at timestamp(6),
        screen_name varchar(255),
        primary key (id)
    );

    create table tb_seat (
        seat_number integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        screen_fk bigint,
        updated_at timestamp(6),
        seat_row varchar(255),
        seat_type varchar(255) check (seat_type in ('STANDARD','VIP','PWD')),
        primary key (id)
    );

    create table tb_session (
        has_subtitles boolean not null,
        is_threed boolean not null,
        pwd_seat_price numeric(38,2),
        standard_seat_price numeric(38,2),
        vip_seat_price numeric(38,2),
        created_at timestamp(6),
        end_time timestamp(6),
        id bigint generated by default as identity,
        movie_fk bigint,
        screen_fk bigint,
        start_time timestamp(6),
        updated_at timestamp(6),
        audio_language varchar(255) check (audio_language in ('ENGLISH','SPANISH','FRENCH','GERMAN','JAPANESE','CHINESE','KOREAN','PORTUGUESE','ITALIAN','RUSSIAN')),
        primary key (id)
    );

    create table tb_theater (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        logo_url varchar(2048),
        full_address_line varchar(255),
        theater_name varchar(255),
        primary key (id)
    );

    create table tb_user (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        refresh_token varchar(1024),
        email varchar(255),
        password_hash varchar(255),
        user_name varchar(255),
        user_role varchar(255) check (user_role in ('CUSTOMER','ADMIN')),
        primary key (id)
    );

    alter table if exists tb_booked_seat 
       add constraint FKiltdbtgocpogxl4objv3taj50 
       foreign key (booking_id) 
       references tb_booking;

    alter table if exists tb_booked_seat 
       add constraint FKen7wjc4a1f4ae6y4b1og9wldd 
       foreign key (seat_id) 
       references tb_seat;

    alter table if exists tb_booking 
       add constraint FK5gx2xicie84bc363yrqim3a1q 
       foreign key (session_fk) 
       references tb_session;

    alter table if exists tb_booking 
       add constraint FK9tjhqri66nvtjbwb0rxk9namt 
       foreign key (user_fk) 
       references tb_user;

    alter table if exists tb_screen 
       add constraint FKf7x5jde5g6yvp6rdf1sctdmi 
       foreign key (theater_fk) 
       references tb_theater;

    alter table if exists tb_seat 
       add constraint FKs6pygyitnrxq7obpx905onkr 
       foreign key (screen_fk) 
       references tb_screen;

    alter table if exists tb_session 
       add constraint FK9qxa0ly74flir4tlg5ab4rbft 
       foreign key (movie_fk) 
       references tb_movie;

    alter table if exists tb_session 
       add constraint FKqbjt2vf1tmjkktusij10y5a35 
       foreign key (screen_fk) 
       references tb_screen;